# Generated by Django 3.0.5 on 2023-03-04 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0019_receptionist'),
    ]

    operations = [
        migrations.AddField(
            model_name='receptionist',
            name='address',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='receptionist',
            name='mobile',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
