# Generated by Django 3.0.5 on 2023-03-04 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0020_auto_20230304_1346'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='prescription',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='patient',
            name='tests',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
