# Generated by Django 3.0.5 on 2023-03-04 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0023_auto_20230304_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='prescription',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='tests',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
