# Generated by Django 3.0.5 on 2023-03-05 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0025_auto_20230305_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='prescription',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='tests',
            field=models.CharField(max_length=100),
        ),
    ]
