# Generated by Django 3.0.5 on 2023-03-05 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0027_auto_20230305_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='prescription',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='patient',
            name='tests',
            field=models.CharField(default='', max_length=100),
        ),
    ]
