# Generated by Django 3.0.5 on 2023-03-05 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0029_auto_20230305_1217'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='prescription',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='tests',
        ),
    ]
