# Generated by Django 3.0.5 on 2023-03-05 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0030_auto_20230305_1759'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='prescription',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='tests',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
