# Generated by Django 3.0.5 on 2023-03-06 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0038_deo_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deo',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
