# Generated by Django 3.0.5 on 2023-03-11 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0039_auto_20230306_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientdischargedetails',
            name='testresults',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
